name: Core tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [ubuntu-latest]
    defaults:
      run:
        working-directory: ./src/student_management/
    
    strategy:
      matrix:
        python-version: [3.8]

    env:
      MODE: "dev"
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}
      
      - name: Install dependencies
        run: |
          sudo apt-get install freeglut3-dev
          python -m pip install --upgrade pip
          pip install -r ../../requirements.txt

      - name: Test App Code
        run: python ../../tests/main_test.py